# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        args: ['--line-length', '99']
        language_version: python3
        additional_dependencies: ['click==8.0.4'] #https://github.com/psf/black/issues/2964#issuecomment-1080974737
        exclude: |
            ^(
            \.venv
            |build
            |dist
            |\.eggs
            |\.git
            |\.mypy_cache
            |\.tox
            |\.nox
            |\.vscode
            |_build
            |buck-out
            |build-lib
            |contrib
            |dist-newstyle
            |doc/build
            |docs/_build
            |eggs
            |htmlcov
            |node_modules
            |parts
            |sdist
            |var
            )/
-   repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
        args:
        -   --max-line-length=99
        -   --ignore=E501,W503,F405
        # E501: line too long (82 > 79 characters)
        # W503: line break before binary operator
        # F405: undefined names from wildcard imports
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        always_run: true
        files: ^test_ # tests/  # or "^test_" if your test files start with 'test_'
    -   id: sphinx
        name: sphinx-build
        entry: sphinx-build -b html docs/ docs/_build/
        language: system
        pass_filenames: false
        types: [python]
    -   id: twine
        name: twine-check-and-upload
        entry: bash -c "twine check dist/* && twine upload -r testpypi dist/*"
        language: system
        pass_filenames: false
        stages: [manual]
